[2022-01-27T19:34:32.808] [ERROR] myError - Error: Error al insertar Productos campos requeridos
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:51:23)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:35:44.873] [ERROR] myError - Error: Error al insertar Productos campos requeridos
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:51:23)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:39:46.069] [ERROR] myError - Error: Error al insertar Productos campos requeridos
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:51:23)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:42:06.763] [ERROR] myError - Error: Error al insertar Productos campos requeridos
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:51:23)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:48:34.019] [ERROR] myError - TypeError: productosDao.find is not a function
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:15:49)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:53:04.337] [ERROR] myError - TypeError: Cannot read property 'json' of undefined
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:32:21)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:54:03.344] [ERROR] myError - TypeError: Cannot read property 'json' of undefined
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:31:21)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\layer.js:95:5)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\router\index.js:47:12)
[2022-01-27T19:55:45.342] [ERROR] myError - Error: productos validation failed: nombre: Path `nombre` is required., descripcion: Path `descripcion` is required., codigo: Path `codigo` is required., foto: Path `foto` is required., precio: Path `precio` is required., stock: Path `stock` is required.
    at ValidationError.inspect (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\error\validation.js:48:26)
    at internal/per_context/primordials.js:23:32
    at formatValue (internal/util/inspect.js:783:19)
    at inspect (internal/util/inspect.js:337:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2016:40)
    at Object.format (internal/util/inspect.js:1890:10)
    at basicLayout (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\log4js\lib\layouts.js:62:57)
    at app (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\log4js\lib\appenders\file.js:64:23)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\log4js\lib\log4js.js:42:5
    at Array.forEach (<anonymous>) {
  errors: {
    nombre: ValidatorError: Path `nombre` is required.
        at validate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1277:13)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1210:14)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:2690:18
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'nombre',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    descripcion: ValidatorError: Path `descripcion` is required.
        at validate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1277:13)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1210:14)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:2690:18
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'descripcion',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    codigo: ValidatorError: Path `codigo` is required.
        at validate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1277:13)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaNumber.SchemaType.doValidate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1210:14)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:2690:18
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'codigo',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    foto: ValidatorError: Path `foto` is required.
        at validate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1277:13)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1210:14)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:2690:18
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'foto',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    precio: ValidatorError: Path `precio` is required.
        at validate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1277:13)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaNumber.SchemaType.doValidate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1210:14)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:2690:18
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'precio',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    stock: ValidatorError: Path `stock` is required.
        at validate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1277:13)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaNumber.SchemaType.doValidate (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1210:14)
        at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:2690:18
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      properties: [Object],
      kind: 'required',
      path: 'stock',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'productos validation failed'
}
[2022-01-27T19:55:59.990] [ERROR] myError - TypeError: Cannot read property 'json' of undefined
    at crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:31:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2022-01-27T20:19:45.005] [ERROR] myError - CastError: Cast to Number failed for value "61f327ad33b37be8844db3dd" (type string) at path "id" for model "productos"
    at model.Query.exec (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4545:21)
    at model.Query.Query.then (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4644:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  messageFormat: undefined,
  stringValue: '"61f327ad33b37be8844db3dd"',
  kind: 'Number',
  value: '61f327ad33b37be8844db3dd',
  path: 'id',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert.ok(!isNaN(val))
  
      at castNumber (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast\number.js:28:10)
      at SchemaNumber.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:378:12)
      at SchemaNumber.SchemaType.applySetters (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1135:12)
      at SchemaNumber.SchemaType._castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1567:15)
      at SchemaNumber.castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:432:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1534:20)
      at cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast.js:336:32)
      at model.Query.Query.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4968:12)
      at model.Query.Query._castConditions (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2056:10)
      at model.Query.<anonymous> (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2335:8) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  },
  valueType: 'string'
}
[2022-01-27T20:21:43.106] [ERROR] myError - CastError: Cast to Number failed for value "61f327ad33b37be8844db3dd" (type string) at path "id" for model "productos"
    at model.Query.exec (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4545:21)
    at model.Query.Query.then (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4644:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  messageFormat: undefined,
  stringValue: '"61f327ad33b37be8844db3dd"',
  kind: 'Number',
  value: '61f327ad33b37be8844db3dd',
  path: 'id',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert.ok(!isNaN(val))
  
      at castNumber (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast\number.js:28:10)
      at SchemaNumber.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:378:12)
      at SchemaNumber.SchemaType.applySetters (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1135:12)
      at SchemaNumber.SchemaType._castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1567:15)
      at SchemaNumber.castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:432:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1534:20)
      at cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast.js:336:32)
      at model.Query.Query.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4968:12)
      at model.Query.Query._castConditions (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2056:10)
      at model.Query.<anonymous> (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2335:8) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  },
  valueType: 'string'
}
[2022-01-28T18:33:14.234] [ERROR] myError - Error: productos validation failed: codigo: Cast to Number failed for value "Mesa" (type string) at path "codigo"
    at ValidationError.inspect (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\error\validation.js:48:26)
    at internal/per_context/primordials.js:23:32
    at formatValue (internal/util/inspect.js:783:19)
    at inspect (internal/util/inspect.js:337:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2016:40)
    at Object.format (internal/util/inspect.js:1890:10)
    at basicLayout (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\log4js\lib\layouts.js:62:57)
    at app (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\log4js\lib\appenders\file.js:64:23)
    at E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\log4js\lib\log4js.js:42:5
    at Array.forEach (<anonymous>) {
  errors: {
    codigo: CastError: Cast to Number failed for value "Mesa" (type string) at path "codigo"
        at SchemaNumber.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:380:11)
        at SchemaNumber.SchemaType.applySetters (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1135:12)
        at model.$set (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:1407:20)
        at model.$set (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:1149:16)
        at model.Document (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:158:12)
        at model.Model (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\model.js:106:12)
        at new model (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\model.js:4763:15)
        at ProductosDaoMongo.save (E:\Users\Fede\Documents\DESA\backend\clase42\contenedores\ContenedorMongo.js:47:34)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async crearProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:25:29) {
      stringValue: '"Mesa"',
      messageFormat: undefined,
      kind: 'Number',
      value: 'Mesa',
      path: 'codigo',
      reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
      
        assert.ok(!isNaN(val))
      
          at castNumber (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast\number.js:28:10)
          at SchemaNumber.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:378:12)
          at SchemaNumber.SchemaType.applySetters (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1135:12)
          at model.$set (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:1407:20)
          at model.$set (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:1149:16)
          at model.Document (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\document.js:158:12)
          at model.Model (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\model.js:106:12)
          at new model (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\model.js:4763:15)
          at ProductosDaoMongo.save (E:\Users\Fede\Documents\DESA\backend\clase42\contenedores\ContenedorMongo.js:47:34)
          at processTicksAndRejections (internal/process/task_queues.js:93:5) {
        generatedMessage: true,
        code: 'ERR_ASSERTION',
        actual: false,
        expected: true,
        operator: '=='
      },
      valueType: 'string'
    }
  },
  _message: 'productos validation failed'
}
[2022-01-28T19:57:19.189] [ERROR] myError - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\response.js:267:15)
    at eliminarProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:110:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[2022-01-28T19:58:34.040] [ERROR] myError - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\express\lib\response.js:267:15)
    at eliminarProducto (E:\Users\Fede\Documents\DESA\backend\clase42\controllers\productoController.js:110:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[2022-01-28T20:00:21.536] [ERROR] myError - CastError: Cast to Number failed for value "61f4752ec5122cf4c4328d41" (type string) at path "id" for model "productos"
    at model.Query.exec (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4545:21)
    at model.Query.Query.then (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4644:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  messageFormat: undefined,
  stringValue: '"61f4752ec5122cf4c4328d41"',
  kind: 'Number',
  value: '61f4752ec5122cf4c4328d41',
  path: 'id',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert.ok(!isNaN(val))
  
      at castNumber (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast\number.js:28:10)
      at SchemaNumber.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:378:12)
      at SchemaNumber.SchemaType.applySetters (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1135:12)
      at SchemaNumber.SchemaType._castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1567:15)
      at SchemaNumber.castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:432:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1534:20)
      at cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast.js:336:32)
      at model.Query.Query.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4968:12)
      at model.Query.Query._castConditions (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2056:10)
      at model.Query.<anonymous> (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2335:8) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  },
  valueType: 'string'
}
[2022-01-28T20:01:24.688] [ERROR] myError - CastError: Cast to Number failed for value "61f4752ec5122cf4c4328d41" (type string) at path "id" for model "productos"
    at model.Query.exec (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4545:21)
    at model.Query.Query.then (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4644:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  messageFormat: undefined,
  stringValue: '"61f4752ec5122cf4c4328d41"',
  kind: 'Number',
  value: '61f4752ec5122cf4c4328d41',
  path: 'id',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert.ok(!isNaN(val))
  
      at castNumber (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast\number.js:28:10)
      at SchemaNumber.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:378:12)
      at SchemaNumber.SchemaType.applySetters (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1135:12)
      at SchemaNumber.SchemaType._castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1567:15)
      at SchemaNumber.castForQuery (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schema\number.js:432:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\schematype.js:1534:20)
      at cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\cast.js:336:32)
      at model.Query.Query.cast (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:4968:12)
      at model.Query.Query._castConditions (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2056:10)
      at model.Query.<anonymous> (E:\Users\Fede\Documents\DESA\backend\clase42\node_modules\mongoose\lib\query.js:2335:8) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  },
  valueType: 'string'
}
